/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CategoryListItem {
        /**
          * The items array
         */
        "category": any;
    }
    interface GlossaryTerm {
        /**
          * The items array
         */
        "term": any;
    }
}
declare global {
    interface HTMLCategoryListItemElement extends Components.CategoryListItem, HTMLStencilElement {
    }
    var HTMLCategoryListItemElement: {
        prototype: HTMLCategoryListItemElement;
        new (): HTMLCategoryListItemElement;
    };
    interface HTMLGlossaryTermElement extends Components.GlossaryTerm, HTMLStencilElement {
    }
    var HTMLGlossaryTermElement: {
        prototype: HTMLGlossaryTermElement;
        new (): HTMLGlossaryTermElement;
    };
    interface HTMLElementTagNameMap {
        "category-list-item": HTMLCategoryListItemElement;
        "glossary-term": HTMLGlossaryTermElement;
    }
}
declare namespace LocalJSX {
    interface CategoryListItem {
        /**
          * The items array
         */
        "category"?: any;
        /**
          * Testing an event without value
         */
        "onViewItemEvent"?: (event: CustomEvent<any>) => void;
    }
    interface GlossaryTerm {
        /**
          * The items array
         */
        "term"?: any;
    }
    interface IntrinsicElements {
        "category-list-item": CategoryListItem;
        "glossary-term": GlossaryTerm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "category-list-item": LocalJSX.CategoryListItem & JSXBase.HTMLAttributes<HTMLCategoryListItemElement>;
            "glossary-term": LocalJSX.GlossaryTerm & JSXBase.HTMLAttributes<HTMLGlossaryTermElement>;
        }
    }
}
